# Generated by Django 6.0 on 2026-01-01 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultingFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, unique=True)),
                ('time_frame', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('permit_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.client')),
                ('consulting_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.consultingfirm')),
                ('principal_contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.principalcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField()),
                ('audit_type', models.CharField(choices=[('OHS', 'Occupational Health & Safety Audit'), ('ENV', 'Environmental Audit'), ('QUAL', 'Quality Audit')], default='OHS', max_length=10)),
                ('audit_number', models.CharField(max_length=50)),
                ('performed_by', models.CharField(max_length=200)),
                ('report_number', models.CharField(max_length=100)),
                ('overall_score_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('standard_required', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('improvement_notices', models.IntegerField(default=0)),
                ('contravention_notices', models.IntegerField(default=0)),
                ('prohibition_notices', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.project')),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('regulation_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_to', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='audit.audit')),
                ('risk_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit.riskrating')),
            ],
        ),
        migrations.CreateModel(
            name='SitePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_personnel', models.IntegerField(default=0)),
                ('management_count', models.IntegerField(blank=True, default=0, null=True)),
                ('worker_count', models.IntegerField(blank=True, default=0, null=True)),
                ('subcontractor_count', models.IntegerField(blank=True, default=0, null=True)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='audit.audit')),
            ],
        ),
        migrations.CreateModel(
            name='VisualObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('observation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_observations', to='audit.audit')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PPE_ISSUED', 'PPE Issued and being worn (free of charge)'), ('AWARENESS', 'Employees are aware of their OHS duties'), ('PROCEDURES', 'Procedure for addressing OHS concerns')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protection_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='FirePrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('EQUIPMENT_AVAILABLE', 'Suitable fire extinguishing equipment available'), ('FIRE_FIGHTER_APPOINT', 'Fire fighter Appointment'), ('AWARENESS', 'Employees aware of emergency procedures'), ('COMPETENCIES', 'Fire Fighter Competencies'), ('EVACUATION_PLAN', 'Fire emergency evacuation layout plan visible'), ('EVACUATION_DRILL', 'Fire emergency evacuation drill conducted'), ('EMERGENCY_CONTACTS', 'Emergency Contact numbers in place')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_prevention_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='IncidentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PROCEDURE', 'Incident Management Procedure'), ('ANNEXURE', 'Annexure.1'), ('WCL_FORMS', 'WCL1 - WCL6 forms available'), ('DISCIPLINARY_PROC', 'Disciplinary Procedure in place'), ('NEAR_MISS', 'Near – miss records'), ('FIRST_AID_RECORDS', 'First Aid Injury Records')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='InspectionRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_type', models.CharField(choices=[('HS_REP_CHECKLIST', 'Health and Safety Rep Inspection Checklist'), ('FIRST_AID_BOX', 'First Aid Box Inspection Registers'), ('FIRE_EQUIPMENT', 'Fire Extinguishing Equipment Register'), ('FACILITIES_HYGIENE', 'Facilities/hygiene Inspection Register'), ('STACKING_STORAGE', 'Stacking & Storage Register'), ('HAND_TOOL', 'Hand Tool Register'), ('MOBILE_PLANT', 'Mobile Plant Checklists'), ('PPE_REGISTER', 'PPE Registers'), ('INCIDENT_REGISTER', 'Incident Registers'), ('EXCAVATION', 'Excavation Inspection Register'), ('HOUSEKEEPING', 'Housekeeping Checklist'), ('VEHICLE_PRE_START', 'Construction Vehicle Pre-Start Checklist'), ('SIGNAGE', 'Signage Checklist'), ('HYGIENE', 'Hygiene Checklist')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_registers', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'register_type')},
            },
        ),
        migrations.CreateModel(
            name='IntoxicationManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('RANDOM_TESTING', 'Random Alcohol testing'), ('DISCIPLINARY_PROC', 'Disciplinary Procedure in place'), ('ALCOHOL_DRUGS_POLICY', 'Alcohol and Drugs Policy'), ('BREATHALYSER', 'Breathalyser')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intoxication_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='LegalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('CEO_16_1', 'Chief Executive Officer Sec 16.1'), ('CEO_16_2', 'Assistant CEO Sec 16.2'), ('CONSTR_MGR_8_1', 'Construction Manager CR 8.1'), ('HCA', 'HCA (Reg 2020)'), ('CONSTR_SUP_8_7', 'Construction Supervisor CR 8.7'), ('ELEC_INSP', 'Electrical Equipment Inspector Controller'), ('CHS_OFFICER_8_5', 'Construction Health and Safety Officer CR 8.5'), ('FIRE_INSP_29H', 'Fire Equipment Inspector CR 29(h)'), ('ENV_OFFICER', 'Environmental Officer'), ('EMERGENCY_COORD', 'Emergency Coordinator'), ('HS_REP_17_1', 'Health and Safety Representative Sec 17.1'), ('EXCAV_SUP_13_1', 'Excavation Supervisor CR 13(1)'), ('RISK_ASSESSOR_9_1', 'Risk Assessor CR 9.(1)'), ('PPE_INSP', 'PPE Inspector'), ('FIRST_AIDER', 'First Aider'), ('HAND_TOOLS_INSP', 'Hand Tools Inspector Sec 8.2i'), ('STACKING_STORAGE', 'Stacking and Storage Supervisor CR 28(a)'), ('HS_COMMITTEE', 'Health and Safety Committee Member'), ('HYGIENE_INSP', 'Hygiene and Facility Inspector'), ('INCIDENT_INVEST', 'Incident Investigator CR 29(h)'), ('PORTABLE_ELEC_INSP', 'Portable Elec. Tools Inspector EMR 10'), ('HOUSEKEEPING', 'Housekeeping CR 27'), ('VEHICLE_INSP', 'CR 23 Construction Vehicle and Mobile Plant Inspector'), ('TRAFFIC_SAFETY', 'Traffic Safety Officer'), ('HS_CHAIRPERSON', 'Chairperson Health and Safety Committee Sec 19'), ('VEHICLE_OPERATOR', 'CR 23 Construction vehicle and Mobile Plant operator')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 'Non-Compliant'), (1, 'Partial Compliance'), (2, 'Fully Compliant')])),
                ('appointed_person', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_appointments', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'appointment_type')},
            },
        ),
        migrations.CreateModel(
            name='OccupationalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ENTRY_MEDICAL_EXAM', 'Entry Medical Examinations'), ('MEDICAL_COPIES', 'Copies of medical examinations on file'), ('ID_COPIES', 'ID copies on site')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupational_health_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='OHSDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SHE_FILE', 'SHE File on site'), ('CLIENT_SPECS', 'Clients Safety Specifications CR 9'), ('RISK_ASSESSMENT', 'Baseline Risk Assessment'), ('CONSTRUCTION_NOTICE', 'Notification of Construction'), ('COIDA', 'COIDA Letter of good standing'), ('INCIDENT_REGISTERS', 'Incident Registers'), ('WCL_FORMS', 'WCL1 – WCL6 Forms'), ('ACT_DISPLAY', 'Copy of Act display on site'), ('CONTRACTOR_APPOINTMENT', 'Contractors Appointment CR.5(1)(K)'), ('MANDATORY_AGREEMENTS', 'Signed Mandatory Agreements'), ('POLICIES', 'Polices to be updated')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohs_documents', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='PublicSafetySecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('ACCESS_CONTROL', 'Access Control Register'), ('GUARDHOUSE', 'Guardhouse On site'), ('SECURITY_PERSONNEL', 'Security Personnel on site'), ('PSIRA_REGISTRATION', 'PSIRA Registered security appointment'), ('SECURITY_RISK_ASSESS', 'Security Risk Assessment'), ('FIRE_EXTINGUISHER', 'Fire Extinguisher'), ('SECURITY_LETTER', 'Letter of Good Standing (Security)'), ('SECURITY_MEDICAL', 'Medical certificate (Security)'), ('SECURITY_AGREEMENT', 'Mandatory Agreement (Security)'), ('SECURITY_APPOINTMENT', 'Appointment Letter (Security)'), ('PSIRA_REG', 'PSIRA Registration'), ('SECURITY_PPE', 'PPE (Security)')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='TrafficAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FLAG_PEOPLE_TRAINED', 'Flag people trained for this job'), ('SIGNS_UPDATED', 'Signs updated before start and end of shift'), ('UPDATE_REGISTER', 'Register for update records'), ('ROAD_CLEAN', 'Existing road is clean and free from danger'), ('DEVIATION_DAMPED', 'Deviations damped with water to minimize dust'), ('DEVIATION_BLADED', 'Deviation bladed if required'), ('CHILDREN_PROTECTION', 'Children free from being injured'), ('VEHICLES_CONDITION', 'Construction vehicles in good conditions'), ('SAFETY_FEATURES', 'Safety features on construction vehicles'), ('OPENINGS_BARRICADED', 'All openings are barricaded'), ('FLAG_POSITIONS', 'Flag people always in required positions'), ('SIGNS_PLACEMENT', 'Signs placed according to specifications'), ('SIGNS_REGISTER', 'Signs register updated daily')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='TrainingCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('INDUCTION_MANUAL', 'Health and Safety Induction Manual'), ('SAFETY_TALKS', 'Health and Safety Talks'), ('DAILY_RISK_ASSESS', 'Daily Task Risk Assessments'), ('TRAFFIC_MEETINGS', 'Daily Traffic Accommodation Meetings')], max_length=50)),
                ('required_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=2)),
                ('actual_score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_items', to='audit.audit')),
            ],
            options={
                'unique_together': {('audit', 'item_type')},
            },
        ),
    ]
