# Generated by Django 6.0 on 2026-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalappointment',
            name='appointment_type',
            field=models.CharField(choices=[('CEO_16_1', 'Chief Executive Officer Sec 16.1'), ('CEO_16_2', 'Assistant CEO Sec 16.2'), ('CONSTR_MGR_8_1', 'Construction Manager CR 8.1'), ('HCA', 'HCA (Reg 2020)'), ('CONSTR_SUP_8_7', 'Construction Supervisor CR 8.7'), ('ELEC_INSP', 'Electrical Equipment Inspector Controller'), ('CHS_OFFICER_8_5', 'Construction Health and Safety Officer CR 8.5'), ('FIRE_INSP_29H', 'Fire Equipment Inspector CR 29(h)'), ('ENV_OFFICER', 'Environmental Officer'), ('EMERGENCY_COORD', 'Emergency Coordinator'), ('HS_REP_17_1', 'Health and Safety Representative Sec 17.1'), ('EXCAVATION_SUP_13_1', 'Excavation Supervisor CR 13(1)'), ('RISK_ASSESSOR_9_1', 'Risk Assessor CR 9.(1)'), ('PPE_INSP', 'PPE Inspector'), ('FIRST_AIDER', 'First Aider'), ('HAND_TOOLS_INSP', 'Hand Tools Inspector Sec 8.2i'), ('STACKING_STORAGE', 'Stacking and Storage Supervisor CR 28(a)'), ('HS_COMMITTEE', 'Health and Safety Committee Member'), ('HYGIENE_INSP', 'Hygiene and Facility Inspector'), ('INCIDENT_INVEST', 'Incident Investigator CR 29(h)'), ('PORTABLE_ELEC_INSP', 'Portable Elec. Tools Inspector EMR 10'), ('HOUSEKEEPING', 'Housekeeping CR 27'), ('VEHICLE_INSP', 'CR 23 Construction Vehicle and Mobile Plant Inspector'), ('TRAFFIC_SAFETY', 'Traffic Safety Officer'), ('HS_CHAIRPERSON', 'Chairperson Health and Safety Committee Sec 19'), ('VEHICLE_OPERATOR', 'CR 23 Construction vehicle and Mobile Plant operator')], max_length=50),
        ),
    ]
