# Generated by Django 6.0 on 2026-01-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_client_address_client_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='employee_count',
        ),
    ]
